// プロジェクトから直接ランチャ「.NET Core Launch (web) with Remote」で起動した場合は、
// 下記の変数を有効にしてください。
@hostname = localhost
@port = 30202

@host = {{hostname}}:{{port}}

###
# ブローカーのトピック一覧を取得します。
GET http://{{host}}/WeatherForecast
